  version: "2"
  services:  
    postgres:
      image: postgres:11
      env_file: redash.env
      restart: always
      environment:
        POSTGRES_USER: OSTGRES_USER   
        POSTGRES_PASSWORD: POSTGRES_PASSWORD    
        POSTGRES_DB : POSTGRES_DB 
      ports:
        - "5432:5432"  
      volumes:
        - ./data/postgres_data:/var/lib/postgresql/data
      logging:
          options:
              max-size: 10m
              max-file: "3"

              
#  database:
#     image: "postgres:11"
#     container_name: ${CONTAINER_NAME:-database}
#     ports:
#       - "5432:5432"
#     expose:
#       - "5432"
#     environment:
#       POSTGRES_DB: "${POSTGRES_DB}"
#       POSTGRES_HOST: "${POSTGRES_HOST}"
#       POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
#       POSTGRES_PORT: "${POSTGRES_PORT}"
#       POSTGRES_USER: "${POSTGRES_USER}"
 
    pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: root@root.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
      volumes:
        - ./data/pgadmin-data:/var/lib/pgadmin